### ISSUE TITLE
Pop-Up nur auf Startseite

### ISSUE THREAD

**Issue by swinde** [vanilla-thunder/bla-popup#1]
Hallo, ich hätte eine Frage: 
Kann man die Funktion auf die Startseite begrenzen?
Derzeit wird das Pop-up bei jedem Seitenaufruf erneut angezeigt.

**Comment by vanilla-thunder** [comment]
nur Startseite wäre doof, weil Kunden über Suchmaschinen auf jeder Seite einsteigen könnten.
Der Popup sollte aber nicht immer wieder angezeigt werden, prüfe mal folgende zwei Moduleinstellungen:
- ein Wert für den Cookie muss hinterlegt sein
- Debug Modus ist ausgeschaltet

**Comment by swinde** [comment]
> ein Wert für den Cookie muss hinterlegt sein.
Das war es, ich hatte mich nicht getraut da was reinzuschreiben. Sorry!
